/** Experimental scoped reported propositions; no territorial atom or world-state promotion. */
import {createHash} from 'node:crypto';
import {validateDataset,type HistoricalDataset,type HistoricalTime,type Unknown} from '../substrate.js';
import {materializeRound4,type Round4} from '../round4/reconstruction.js';
import {composeSourceAssertions,assertSourceAssertionContract} from '../round5/source-contract.js';
import type {ProjectState,RealityStateValue} from '../../../types.js';
import {validateDocumentary,traceDocumentary,type Round3} from '../round3/lineage.js';
export interface Scope6 {spatial:string;functional:string;actor:string;population:string;infrastructure:string;temporal_key:string}
export interface Row6 {id:string;case_id:string;place_id:string;actor_id:string;dimension:string;assertion_form:string;value:string|Unknown;scope:Scope6;time:HistoricalTime;time_role:string;claim_ids:string[];record_ids:string[];source_content_certainty:string;source_identity_certainty:string;reality_certainty:string;competing_claim_ids:string[];unknown_reason:string;canonical_state:false;exclusivity:string;limit:string}
export interface Round6 {schema_version:'historical-reality-experimental/round6';parents:Round4['parents'] & {round4_sha256:string;round5_inventory_sha256:string};delta:Round4['delta'];places:{id:string;label:string;kind:string;contemporary_designations:string[];claim_ids:string[];identity_basis:string;coordinates:null;polygon:null;modern_locator:Unknown}[];rows:Row6[];cases:{id:string;label:string;window_raw:string;place_ids:string[];selection_reason:string;selection_limit:string;row_ids:string[];reconstruction:{id:string;version:1;previous_version_id:null;evaluated_at:string;evidence_cutoff:string;dataset_basis:string;method:string;row_ids:string[];opposition:string;alternatives:string[];canonical_territorial_controller:null}}[];contrasts:{id:string;left_id:string;right_id:string;claim_ids:string[];manual_alignment_basis:string;category:string;world_contradiction:false}[];chains:{id:string;claim_ids:string[];stages:string[];unknown_edges:Unknown[];knowledge_generated:false}[];searches:{id:string;what:string;where:string;query_or_locator:string;searched_on:string;result:string;classification:string;limitation:string;absence_inference:false}[];b_revalidation:{candidate_id:string;semantic_name:string;classification_before:string;classification_after:string;used:boolean;status:string;claim_ids:string[];finding:string;failed:boolean;promoted:false}[];composition_proofs:{id:string;round5_claim_id:string;round6_claim_id:string;contract:string;limit:string}[];assets:{id:string;source_id:string;path:string;sha256:string;bytes:number;format:string;origin_url:string;inspection:string}[]}
const hash=(b:string)=>createHash('sha256').update(b).digest('hex');
export type Documentary6=Round3['documentary'];
export interface Round6 {documentary:Documentary6;dependencies:{id:string;claim_ids:string[];source_ids:string[];scope:string;mechanism:string;independent_source_count:null;limit:string}[]}
export const documentaryAdapter6=(r:Round6):Round3=>({schema_version:'historical-reality-experimental/round3',parents:r.parents,delta:r.delta,documentary:r.documentary,assets:[]});
export function materializeRound6(p1:string,p2:string,p3:string,p4:string,p5:string,r:Round6):HistoricalDataset {
 if(r.schema_version!=='historical-reality-experimental/round6'||hash(p4)!==r.parents.round4_sha256||hash(p5)!==r.parents.round5_inventory_sha256||hash(p1)!==r.parents.round1_sha256||hash(p2)!==r.parents.round2_sha256||hash(p3)!==r.parents.round3_sha256)throw new Error('Round6 parent integrity/version mismatch');
 const data=structuredClone(materializeRound4(p1,p2,p3,JSON.parse(p4) as Round4));
 for(const k of ['actors','sources','claims','evidence_relations','actor_epistemic_records','reconstructions','interpretations','narratives'] as const)(data[k] as {id:string}[]).push(...structuredClone(r.delta[k]));
 validateTerritory(data,r,JSON.parse(p5));return data;
}
function validDay(day:string){return /^\d{4}-\d{2}-\d{2}$/.test(day)&&!Number.isNaN(Date.parse(day+'T00:00:00Z'))&&new Date(day+'T00:00:00Z').toISOString().slice(0,10)===day}
/** A mismatch is NOT automatically contradiction. Exact comparable exclusive positions still require human alignment. */
export function contrastRows(a:Row6,b:Row6):string {
 if(a.dimension!==b.dimension)return 'different_dimension';
 if(a.assertion_form!==b.assertion_form)return 'different_stage';
 if(a.place_id!==b.place_id||['spatial','functional','population','infrastructure','temporal_key'].some(k=>a.scope[k as keyof Scope6]!==b.scope[k as keyof Scope6]))return 'different_scope';
 if(typeof a.time.normalized_day==='string'&&typeof b.time.normalized_day==='string'&&a.time.normalized_day!==b.time.normalized_day)return 'different_time';
 if(a.value instanceof Object||b.value instanceof Object)return 'unresolved_state_not_negative';
 if(a.value===b.value&&a.actor_id===b.actor_id)return 'same_reported_position';
 if(a.exclusivity==='exclusive'&&b.exclusivity==='exclusive')return 'potential_exclusive_competition_requires_alignment';
 return 'parallel_positions_no_exclusivity_proved';
}
export function validateTerritory(data:HistoricalDataset,r:Round6,inventory?:{candidates:{id:string;classification:string}[]}):void {
 validateDataset(data);validateDocumentary(data,documentaryAdapter6(r));const cs=new Set(data.claims.map(c=>c.id)),actors=new Set(data.actors.map(a=>a.id)),ps=new Map(r.places.map(p=>[p.id,p])),rows=new Map(r.rows.map(x=>[x.id,x])),cases=new Set(r.cases.map(x=>x.id));
 const all=[...r.places,...r.rows,...r.cases,...r.cases.map(x=>x.reconstruction),...r.contrasts,...r.chains,...r.searches,...r.composition_proofs,...r.dependencies,...Object.values(r.documentary).flat()];if(new Set(all.map(x=>x.id)).size!==all.length)throw new Error('Duplicate territorial record');
 const basis=(ids:string[])=>{if(!ids.length||ids.some(id=>!cs.has(id)))throw new Error('Missing territorial provenance root')};
 if(new Set(r.assets.map(a=>a.id)).size!==r.assets.length)throw new Error('Duplicate asset identity');
 for(const a of r.assets)if(!a.id||!data.sources.some(s=>s.id===a.source_id)||!a.path||a.path.startsWith('/')||a.path.split('/').includes('..')||!/^https:\/\//.test(a.origin_url)||!/^[a-f0-9]{64}$/.test(a.sha256)||a.bytes<1||!a.inspection||!['pdf','png','html','json','xml','text'].includes(a.format))throw new Error('Asset provenance required');
 for(const d of r.dependencies){basis(d.claim_ids);if(!d.scope||!d.mechanism||!d.limit||d.independent_source_count!==null||d.source_ids.some(id=>!data.sources.some(s=>s.id===id)))throw new Error('Scoped dependency is not independent corroboration')}
 for(const p of r.places){basis(p.claim_ids);if(!p.identity_basis||!p.label||!p.kind||!p.contemporary_designations.length||p.coordinates!==null||p.polygon!==null)throw new Error('Historical place identity/precision boundary lost')}
 for(const c of r.delta.claims)if(!c.assertion_layer||!c.locator)throw new Error('Attribution layer/locator lost');
 for(const x of r.rows){basis(x.claim_ids);if(!cases.has(x.case_id)||!ps.has(x.place_id)||!actors.has(x.actor_id)||x.scope.actor!==x.actor_id||x.scope.spatial!==x.place_id)throw new Error('Territorial scope reference mismatch');if(!x.dimension||!x.assertion_form||!x.time_role||!x.time.raw||!x.unknown_reason||!x.limit||Object.values(x.scope).some(v=>!v)||x.canonical_state!==false)throw new Error('Territorial scope/certainty boundary lost');
  if(typeof x.time.normalized_day==='string'&&(!validDay(x.time.normalized_day)||x.time.precision!=='day'))throw new Error('Historical time synthesized');
  if(typeof x.time.normalized_day!=='string'&&(!x.time.normalized_day||x.time.normalized_day.status!=='unknown'||!x.time.normalized_day.reason))throw new Error('Unknown temporal scope reason required');
  if(!x.source_content_certainty||!x.source_identity_certainty||!x.reality_certainty||x.competing_claim_ids.some(id=>!cs.has(id)))throw new Error('Scoped certainty/opposition lost');
  if(typeof x.value!=='string'&&(x.value.status!=='unknown'||!x.value.reason||x.reality_certainty!=='unresolved'||x.assertion_form!=='unresolved_state'))throw new Error('Unknown cannot become negative/known reality');
  if(['legal_text','declared_duty','request','undertaking','instruction'].includes(x.assertion_form)&&x.reality_certainty==='strongly_established')throw new Error('Declared right cannot become exercised reality');
  if(x.record_ids.some(id=>!rows.has(id)))throw new Error('Dangling row relation');
 }
 const active=new Set<string>(),seen=new Set<string>();const walk=(id:string)=>{if(active.has(id))throw new Error('Territorial provenance cycle');if(seen.has(id))return;active.add(id);rows.get(id)!.record_ids.forEach(walk);active.delete(id);seen.add(id)};r.rows.forEach(x=>walk(x.id));
 for(const c of r.cases){if(!c.selection_reason||!c.selection_limit||!c.window_raw||!c.row_ids.length||c.place_ids.some(id=>!ps.has(id))||c.row_ids.some(id=>rows.get(id)?.case_id!==c.id))throw new Error('Microcase scope incomplete');const v=c.reconstruction;if(v.version!==1||v.previous_version_id!==null||!v.evidence_cutoff||!v.dataset_basis||!v.method||!v.alternatives.length||Number.isNaN(Date.parse(v.evaluated_at))||v.canonical_territorial_controller!==null||JSON.stringify(v.row_ids)!==JSON.stringify(c.row_ids))throw new Error('Reconstruction basis/cutoff/version lost')}
 for(const c of r.contrasts){basis(c.claim_ids);const a=rows.get(c.left_id),b=rows.get(c.right_id);if(!a||!b||!c.manual_alignment_basis||c.world_contradiction!==false||c.category!==contrastRows(a,b)||c.claim_ids.some(id=>![...a.claim_ids,...b.claim_ids].includes(id)))throw new Error('Unscoped or false territorial contradiction')}
 for(const c of r.chains){basis(c.claim_ids);if(!c.stages.length||c.knowledge_generated!==false||c.unknown_edges.some(g=>g.status!=='unknown'||!g.reason))throw new Error('Sparse chain/knowledge boundary lost')}
 for(const s of r.searches)if(s.absence_inference!==false||!s.limitation||!s.classification||!s.query_or_locator)throw new Error('Missing evidence is not absence');
 const bs=inventory?.candidates.filter(x=>x.classification==='B').map(x=>x.id);if(r.b_revalidation.length!==18||new Set(r.b_revalidation.map(x=>x.candidate_id)).size!==18||bs?.some(id=>!r.b_revalidation.some(x=>x.candidate_id===id)))throw new Error('All18B candidates must be revalidated');
 for(const x of r.b_revalidation){if(!x.finding||x.promoted!==false||x.classification_after!=='B'||!['worked unchanged','required narrower scope','required broader scope','not needed','failed','revealed hidden ambiguity'].includes(x.status))throw new Error('Invalid B revalidation');if(x.used)basis(x.claim_ids);else if(x.status!=='not needed')throw new Error('Unused candidate needs reason')}
 if(r.composition_proofs.length!==9)throw new Error('Nine composition transfers required');for(const p of r.composition_proofs)basis([p.round5_claim_id,p.round6_claim_id]);
}
/** Traverses derived record → atomic attributed Claim → inspected source. Search diagnostics intentionally have no claim root. */
export function traceTerritory(data:HistoricalDataset,r:Round6,id:string){validateTerritory(data,r);if(Object.values(r.documentary).flat().some(x=>x.id===id))return traceDocumentary(data,documentaryAdapter6(r),id);const roots=new Set<string>(),seen=new Set<string>();const walk=(key:string)=>{if(seen.has(key))return;seen.add(key);const row=r.rows.find(x=>x.id===key);if(row){row.claim_ids.forEach(x=>roots.add(x));row.competing_claim_ids.forEach(x=>roots.add(x));row.record_ids.forEach(walk);return}const place=r.places.find(x=>x.id===key);if(place){place.claim_ids.forEach(x=>roots.add(x));return}const c=r.cases.find(x=>x.id===key||x.reconstruction.id===key);if(c){c.row_ids.forEach(walk);c.place_ids.forEach(walk);return}const rec=[...r.contrasts,...r.chains,...r.dependencies].find(x=>x.id===key);if(rec){rec.claim_ids.forEach(x=>roots.add(x));return}throw new Error('Unknown territorial derived record')};walk(id);const claims=data.claims.filter(x=>roots.has(x.id));return {id,records:[...seen],claims,relations:data.evidence_relations.filter(x=>roots.has(x.claim_id)),sources:data.sources.filter(s=>claims.some(c=>c.source_id===s.id)),limit:'Attribution/provenance traversal, not truth or source independence assessment'};}
export interface Query6 {place_id:string;dimension:string;functional:string;assertion_form:string;day:string;actor_id?:string;population?:string;infrastructure?:string}
/** Enrich the unchanged R5 content contract with attributed scoped mentions, using existing Claim JSON values. Not an ontic import. */
export function composeTerritorialAssertions(data:HistoricalDataset,r:Round6,state:ProjectState,at:string){validateTerritory(data,r);const patch=composeSourceAssertions(data,state,at);for(const op of patch.operations)if(op.entity==='claim'&&op.payload){const v=op.payload.value as Record<string,RealityStateValue>;const original=(v.attributed_claim as any).id;const rs=r.rows.filter(x=>[...x.claim_ids,...x.competing_claim_ids].includes(original));if(rs.length)op.payload.value={...v,territorial_composition:JSON.parse(JSON.stringify({contract:'territorial-attributed-mentions/v1',rows:rs,places:r.places.filter(p=>rs.some(x=>x.place_id===p.id)),scope:'Source-attributed mentions only; related rows are reconstruction context, not assertions that every supported record is factual. Unknown targets remain unknown.'}))}}return patch;}
export function assertTerritorialProjection(state:ProjectState,data:HistoricalDataset,r:Round6){for(const c of state.claims){assertSourceAssertionContract(state,c.id);const v=c.value as any;const rs=r.rows.filter(x=>[...x.claim_ids,...x.competing_claim_ids].includes(v.attributed_claim.id));if(rs.length&&(v.territorial_composition?.contract!=='territorial-attributed-mentions/v1'||JSON.stringify(v.territorial_composition.rows)!==JSON.stringify(rs)||JSON.stringify(v.territorial_composition.places)!==JSON.stringify(r.places.filter(p=>rs.some(x=>x.place_id===p.id)))))throw new Error('Territorial attributed scope projection lost');if(JSON.stringify(v.attributed_claim)!==JSON.stringify(data.claims.find(x=>x.id===v.attributed_claim.id)))throw new Error('Original attribution projection lost')}if(state.reality_events.length||state.reality_states.length||state.epistemic_observations.length)throw new Error('Historical reality/observation promoted');}
/** Exact named subject/function/stage; only evidence-dated stages are placed, never continued historical state. */
export function queryTerritory(data:HistoricalDataset,r:Round6,q:Query6){validateTerritory(data,r);if(!r.places.some(p=>p.id===q.place_id)||!q.dimension||!q.functional||!q.assertion_form||!validDay(q.day)||q.actor_id&&!data.actors.some(a=>a.id===q.actor_id))throw new Error('Known place and explicit dimension/function/stage/day required');const xs=r.rows.filter(x=>x.place_id===q.place_id&&x.dimension===q.dimension&&x.scope.functional===q.functional&&x.assertion_form===q.assertion_form&&(!q.actor_id||x.actor_id===q.actor_id)&&(!q.population||x.scope.population===q.population)&&(!q.infrastructure||x.scope.infrastructure===q.infrastructure));return {query:q,before:xs.filter(x=>typeof x.time.normalized_day==='string'&&x.time.normalized_day<q.day),same_day_order_unknown:xs.filter(x=>x.time.normalized_day===q.day),unplaced:xs.filter(x=>typeof x.time.normalized_day!=='string'),after:xs.filter(x=>typeof x.time.normalized_day==='string'&&x.time.normalized_day>q.day),reading:'not_inferred',knowledge:'not_inferred',continued_state:'not_inferred',absence:'not_inferred',limit:'Matches are reported propositions/stages; source dates never impute event time or present-day validity. Regional context is not spatially inherited.'};}
