import assert from 'node:assert/strict';
import {test} from 'node:test';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createEmptyProject,applyPatch} from '../state-engine.js';
import {buildInspectionPatch,idsFor} from '../injections/frus-1904-392-inspection-v1/composition.js';
import {rows,ids,inputs,patch,preflight,hashes,dry,audit,prepared,validatePrepared,backup,sha256,stableSerialize,TARGET_PROJECT,POLICY,BATCH,DRY_RUN,BASELINE,type Completion} from '../injections/historical-batch-v1/package.js';
function base(){const s=createEmptyProject({title:'test',summary:'preserve'});s.project.id=TARGET_PROJECT;s.current_state.project_id=TARGET_PROJECT;return applyPatch(s,buildInspectionPatch(s,DRY_RUN));}
function applied(){const before=base(),after=applyPatch(before,patch(before,DRY_RUN));const receipt:Completion={project_id:TARGET_PROJECT,policy:POLICY,batch_id:BATCH,recorded_at:DRY_RUN,selected_input_hashes:rows.map(r=>r.hash),record_hashes:hashes(after)};return {before,after,receipt};}
test('three selected inputs validate and match pinned fingerprints',()=>{for(const {row,selected} of inputs())assert.equal(sha256(stableSerialize(selected)),row.hash);});
test('all nine approved IDs exact and distinct from 392',()=>{assert.deepEqual(rows.flatMap(r=>Object.values(ids(r))),['a1a0a37c-ceff-5690-a4cb-6e0e551e77d8','5e1617be-3b30-5e4c-a839-53d54a8b9e45','683a6945-aac4-5e5a-a291-887dc192e6b4','2fb4f68c-8a85-55cc-a490-d1e5fc8945b2','cab9db21-5fcc-5c0e-a11d-38a9d15a0e2a','5702ac69-3f61-5c82-ace8-90c4c317dd4f','3d69b18c-d130-5e45-abe3-cb2ee19ce775','560d3816-d4ab-5c43-a7d0-a617f9f1a3bd','30f34e69-460a-5534-ab7c-984d53fcb7a7']);assert.equal(new Set([...rows.flatMap(r=>Object.values(ids(r))),...Object.values(idsFor(TARGET_PROJECT))]).size,12);});
test('exact content, null observed_at, provenance and refs stay scoped',()=>{const {after}=applied();for(const row of rows){const i=ids(row),o=after.epistemic_observations.find(o=>o.id===i.observation)!,e=after.evidence.find(e=>e.id===i.evidence)!;assert.equal(o.content,row.content);assert.equal(o.observed_at,null);assert.deepEqual(o.subject_ids,[i.document]);assert.equal(o.provenance.external_id,`round1.dataset.json#claims/${row.report}`);assert.equal(e.observation_id,o.id);assert.equal(e.kind,'observation_ref');assert.equal(e.external_ref,null);}});
test('only approved delta, metadata, current_state and 392 preservation',()=>{const {before,after}=applied();audit(before,after);const changed=structuredClone(after);changed.current_state.summary='bad';assert.throws(()=>audit(before,changed));});
test('all absent READY; all exact NO_OP; neither mutates input',()=>{const {before,after,receipt}=applied();assert.equal(preflight(before).gate,'READY');const saved=stableSerialize(after);assert.equal(preflight(after,receipt).gate,'NO_OP');assert.equal(stableSerialize(after),saved);});
test('mixed and partial HOLD; missing receipt HOLD',()=>{const {before,after,receipt}=applied();assert.equal(preflight(after).gate,'HOLD');const partial=structuredClone(after);partial.evidence.pop();assert.equal(preflight(partial,receipt).gate,'HOLD');const mixed=structuredClone(after);const i=ids(rows[2]);mixed.reality_entities=mixed.reality_entities.filter(x=>x.id!==i.document);mixed.epistemic_observations=mixed.epistemic_observations.filter(x=>x.id!==i.observation);mixed.evidence=mixed.evidence.filter(x=>x.id!==i.evidence);assert.equal(preflight(mixed,receipt).gate,'HOLD');assert.equal(preflight(before,receipt).gate,'HOLD');});
test('content/provenance/hash/time/identity/extra relation conflicts fail closed',()=>{const {after,receipt}=applied();for(const mutate of [(s:typeof after)=>{s.epistemic_observations[1].content='false';},(s:typeof after)=>{s.evidence[1].provenance.label='changed';},(s:typeof after)=>{s.evidence[1].updated_at='2001-01-01T00:00:00Z';},(s:typeof after)=>{s.reality_entities.push({...s.reality_entities[1],id:'99999999-9999-4999-a999-999999999999'});},(s:typeof after)=>{s.epistemic_observations.push({...s.epistemic_observations[1],id:'99999999-9999-4999-a999-999999999999'});}]){const s=structuredClone(after);mutate(s);assert.equal(preflight(s,receipt).gate,'HOLD');}assert.equal(preflight(after,{...receipt,record_hashes:{}}).gate,'HOLD');});
test('source ID and URL collision without expected ID HOLD',()=>{for(const key of ['source_id','url']){const s=base();s.reality_entities[0].attrs![key]=key==='source_id'?'frus:1904:393':'https://history.state.gov/historicaldocuments/frus1904/d393';assert.equal(preflight(s).gate,'HOLD');}});
test('dry semantics repeat exactly; real mutation timestamps are not normalized backwards',()=>{const s=base(),bytes=stableSerialize(s);assert.deepEqual(dry(s).review,dry(s).review);assert.equal(stableSerialize(s),bytes);const next=dry(s).after;assert.notEqual(next.project.updated_at,DRY_RUN);assert.equal(next.project.updated_at,next.updated_at);assert.deepEqual(patch(s,DRY_RUN).operations.map(x=>x.entity_id),patch(s,'2030-01-01T00:00:00Z').operations.map(x=>x.entity_id));});
test('prepared receipt exact shape, unbound completion fields and tampering rejected',()=>{const p=prepared('a'.repeat(40),'b'.repeat(64));validatePrepared(p);assert.equal(p.final_recorded_at,'UNBOUND');assert.throws(()=>validatePrepared({...p,after_fingerprint:'invented'}));assert.throws(()=>prepared('bad','bad'));});
test('recovery rejects wrong bytes and discovery-contained path',()=>{const dir=mkdtempSync(join(tmpdir(),'batch-recovery-'));try{assert.throws(()=>backup(Buffer.from('wrong'),join(dir,'ops'),join(dir,'projects')));assert.throws(()=>backup(Buffer.from('wrong'),join(dir,'projects','ops'),join(dir,'projects')));}finally{rmSync(dir,{recursive:true,force:true});}});
test('frozen review contains nine full canonical candidates with exact hashes',()=>{const r=JSON.parse(readFileSync(new URL('../injections/historical-batch-v1/dry-review.json',import.meta.url),'utf8'));assert.equal(r.records.length,9);assert.equal(r.final_recorded_at,'UNBOUND');for(const row of r.records)assert.equal(sha256(stableSerialize(row.record)),row.sha256);assert.deepEqual(dry(base()).review.records,r.records);});
test('package fingerprint verifies every frozen dependency',async()=>{const {verifyFreeze}=await import('../injections/historical-batch-v1/freeze.js');assert.match(verifyFreeze(),/^[0-9a-f]{64}$/);});
