import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFileSync } from 'node:fs';
import { createEmptyProject, applyPatch } from '../state-engine.js';
import { buildInspectionPatch } from '../injections/frus-1904-392-inspection-v1/composition.js';
import * as previous from '../injections/historical-batch-v1/package.js';
import { groups,groupIds,inputs,patch,preflight,recordHashes,dry,audit,prepared,validatePrepared,validateCompletion,sha256,stableSerialize,TARGET_PROJECT,DRY_RUN,DELTA,TOTALS,type Completion } from '../injections/historical-expansion-v1/package.js';
import { verifyFreeze } from '../injections/historical-expansion-v1/freeze.js';
import { getObservationsForSubject } from '../reality/epistemic.js';
function base() {
 const state=createEmptyProject({title:'Existing title',summary:'Existing summary'});state.project.id=TARGET_PROJECT;state.current_state.project_id=TARGET_PROJECT;
 const first=applyPatch(state,buildInspectionPatch(state,DRY_RUN));return applyPatch(first,previous.patch(first,DRY_RUN));
}
function applied() {
 const before=base(),after=applyPatch(before,patch(before,DRY_RUN));
 const receipt:Completion={status:'COMPLETED',prepared:prepared('a'.repeat(40),verifyFreeze()),recorded_at:DRY_RUN,after_fingerprint:sha256(stableSerialize(after)),record_hashes:recordHashes(after),independent_read_fingerprint:sha256(stableSerialize(after))};
 return {before,after,receipt};
}
const review=JSON.parse(readFileSync(new URL('../injections/historical-expansion-v1/dry-review.json',import.meta.url),'utf8'));
test('twelve input hashes, content and all IDs independently match tracked discovery and dataset',()=>{const checked=inputs();assert.equal(checked.length,7);assert.equal(checked.flatMap(g=>g.reports).length,12);assert.equal(new Set(groups.flatMap(groupIds)).size,31);for(const {reports} of checked)for(const {report,selected} of reports)assert.equal(sha256(stableSerialize(selected)),report.selected_sha256);});
test('one Document operation per source; report multiplicity 3/2/1/1/1/3/1',()=>{const ops=patch(base(),DRY_RUN).operations;assert.equal(ops.length,31);assert.equal(ops.filter(o=>o.entity==='reality_entity').length,7);assert.deepEqual(groups.map(g=>g.reports.length),[3,2,1,1,1,3,1]);assert.equal(new Set(ops.map(o=>o.entity_id)).size,31);});
test('all report subjects, provenance, null observed_at and independent Evidence refs',()=>{const {after}=applied();for(const g of groups){assert.equal(getObservationsForSubject(after,g.document_id).length,g.reports.length);for(const r of g.reports){const o=after.epistemic_observations.find(o=>o.id===r.observation_id)!,e=after.evidence.find(e=>e.id===r.evidence_id)!;assert.deepEqual(o.subject_ids,[g.document_id]);assert.equal(o.content,r.content);assert.equal(o.kind,'textual');assert.equal(o.observed_at,null);assert.equal(o.recorded_at,DRY_RUN);assert.deepEqual(o.provenance,{kind:'document',external_id:`round1.dataset.json#claims/${r.report_id}`,label:'Stored Historical Round1 inspection report; researcher-authored paraphrase'});assert.deepEqual(e.provenance,o.provenance);assert.equal(e.observation_id,o.id);assert.equal(e.kind,'observation_ref');assert.equal(e.external_ref,null);}}});
test('content qualifiers preserve reported fate, allegation, attribution, translation and conditionality',()=>{const contents=Object.fromEntries(groups.flatMap(g=>g.reports.map(r=>[r.report_id,r.content])));for(const [id,words] of Object.entries({'c395-captured':['reported','attributed','not inspected'],'c395-sunk':['reported','attributed'],'c395-first-fire':['alleged','unverified'],'c678-uncertainty':['no positive knowledge','does not mean complete ignorance'],'c678-sent':['reported through','own view'],'c679-held':['reportedly','does not establish receipt'],'c680-attack':['translated','27th January [9th February]','February 9','February 10','no exact event instant'],'c86-request':['instructs','desire','does not establish'],'c430-consent':['asserts','does not establish'],'c430-guarantee':['Article III','text','does not establish'],'c430-occupation':['Article IV','conditionally','does not establish'],'c815-inquiry':['reportedly','does not establish commission findings']}))for(const word of words)assert(contents[id].includes(word),`${id}: ${word}`);});
test('dry delta and final totals; all existing records and unrelated semantic fields unchanged',()=>{const {before,after}=applied();audit(before,after,DRY_RUN);for(const [k,n] of Object.entries(TOTALS))assert.equal((after as any)[k].length,n);for(const [k,n] of Object.entries(DELTA))assert.equal((after as any)[k].length-(before as any)[k].length,n);assert.equal(before.reality_entities.length,4);assert.equal(before.epistemic_observations.length,4);assert.equal(before.evidence.length,4);});
test('audit rejects changed current_state, metadata, prior record, new content and unknown field',()=>{const {before,after}=applied();for(const mutate of [(s:typeof after)=>{s.current_state.summary='bad';},(s:typeof after)=>{s.project.title='bad';},(s:typeof after)=>{s.evidence[0].summary='bad';},(s:typeof after)=>{s.epistemic_observations[4].content='bad';},(s:typeof after)=>{(s as any).unapproved=true;}]){const s=structuredClone(after);mutate(s);assert.throws(()=>audit(before,s,DRY_RUN));}});
test('all seven absent READY; all exact NO_OP; input remains immutable',()=>{const {before,after,receipt}=applied();assert.deepEqual(preflight(before).per_document.map(g=>g.status),Array(7).fill('NOT_APPLIED'));assert.equal(preflight(before).gate,'READY');const bytes=stableSerialize(after);assert.equal(preflight(after,receipt).gate,'NO_OP');assert.equal(stableSerialize(after),bytes);assert.equal(preflight(after).gate,'HOLD');});
test('mixed exact/absent groups HOLD without conflating per-document states',()=>{const {after,receipt}=applied();const ids=new Set(groupIds(groups[0]));after.reality_entities=after.reality_entities.filter(r=>!ids.has(r.id));after.epistemic_observations=after.epistemic_observations.filter(r=>!ids.has(r.id));after.evidence=after.evidence.filter(r=>!ids.has(r.id));const result=preflight(after,receipt);assert.equal(result.per_document[0].status,'NOT_APPLIED');assert(result.per_document.slice(1).every(g=>g.status==='ALREADY_APPLIED_EXACT'));assert.equal(result.gate,'HOLD');assert.equal(preflight(base(),receipt).gate,'HOLD');});
for(const collection of ['reality_entities','epistemic_observations','evidence'] as const)test(`missing ${collection} record HOLD`,()=>{const {after,receipt}=applied();after[collection].pop();assert.equal(preflight(after,receipt).gate,'HOLD');});
test('Document-only and one missing report pair HOLD',()=>{const {after,receipt}=applied();const g=groups[0];after.epistemic_observations=after.epistemic_observations.filter(x=>x.id!==g.reports[0].observation_id);after.evidence=after.evidence.filter(x=>x.id!==g.reports[0].evidence_id);assert.equal(preflight(after,receipt).gate,'HOLD');const before=base();before.reality_entities.push(after.reality_entities.find(x=>x.id===g.document_id)!);assert.equal(preflight(before).gate,'HOLD');});
for(const name of ['content','provenance','identity','subject','evidence-ref','extra-report','extra-evidence','source-alias','url-alias','other-collection-id','cross-scope-ref'])test(`${name} conflict fails closed`,()=>{const {after,receipt}=applied(),g=groups[0],o=after.epistemic_observations.find(x=>x.id===g.reports[0].observation_id)!,e=after.evidence.find(x=>x.id===g.reports[0].evidence_id)!,doc=after.reality_entities.find(x=>x.id===g.document_id)!;const other='99999999-9999-4999-a999-999999999999';switch(name){case 'content':o.content='actual fact';break;case 'provenance':o.provenance.external_id='wrong';break;case 'identity':doc.label='wrong';break;case 'subject':o.subject_ids=[after.reality_entities[0].id];break;case 'evidence-ref':e.observation_id=after.epistemic_observations[0].id;break;case 'extra-report':after.epistemic_observations.push({...structuredClone(o),id:other,provenance:{...o.provenance,external_id:'unexpected'}});break;case 'extra-evidence':after.evidence.push({...structuredClone(e),id:other});break;case 'source-alias':after.reality_entities.push({...structuredClone(doc),id:other,attrs:{source_id:g.source_id}});break;case 'url-alias':after.reality_entities.push({...structuredClone(doc),id:other,attrs:{url:doc.attrs!.url}});break;case 'other-collection-id':after.evidence[0].id=g.document_id;break;case 'cross-scope-ref':after.epistemic_observations[0].subject_ids.push(g.document_id);break;}assert.equal(preflight(after,receipt).gate,'HOLD');});
test('absent source ID and URL collisions HOLD; unrelated scope allowed',()=>{for(const key of ['source_id','url']){const s=base();s.reality_entities[0].attrs![key]=key==='source_id'?groups[0].source_id:'https://history.state.gov/historicaldocuments/frus1904/d395';assert.equal(preflight(s).gate,'HOLD');}const {after,receipt}=applied();after.epistemic_observations.push({...structuredClone(after.epistemic_observations[0]),id:'99999999-9999-4999-a999-999999999999'});assert.equal(preflight(after,receipt).gate,'NO_OP');});
test('receipt field/membership/hash/binding tampering HOLD',()=>{const {after,receipt}=applied();for(const mutate of [(r:Completion)=>{r.record_hashes[groups[0].document_id]='0'.repeat(64);},(r:Completion)=>{r.prepared.report_ids.pop();},(r:Completion)=>{r.prepared.package_fingerprint='0'.repeat(64);},(r:Completion)=>{r.independent_read_fingerprint='0'.repeat(64);},(r:Completion)=>{r.recorded_at='2030-01-01T00:00:00Z';},(r:Completion)=>{(r as any).extra=true;}]){const r=structuredClone(receipt);mutate(r);assert.equal(preflight(after,r).gate,'HOLD');}});
test('semantic difference remains HOLD even if actual record hash is recomputed',()=>{const {after,receipt}=applied();after.epistemic_observations[4].content='changed';receipt.record_hashes=recordHashes(after);assert.equal(preflight(after,receipt).gate,'HOLD');});
test('dry repeat semantics/grouping/IDs fixed; real mutation clock not in semantic identity',()=>{const s=base(),bytes=stableSerialize(s),a=dry(s),b=dry(s);assert.deepEqual(a.review,b.review);assert.equal(stableSerialize(s),bytes);assert.deepEqual(patch(s,DRY_RUN).operations.map(x=>x.entity_id),patch(s,'2030-01-01T00:00:00Z').operations.map(x=>x.entity_id));assert.notEqual(a.after.updated_at,DRY_RUN);assert.throws(()=>patch(s,'1904-02-09'));});
test('all 31 complete frozen dry candidate hashes and seven grouping structures reproduce',()=>{const result=dry(base()).review;assert.deepEqual(result.groups,review.groups);assert.equal(result.groups.flatMap(g=>g.records).length,31);for(const g of result.groups)for(const r of g.records)assert.equal(sha256(stableSerialize(r.record)),r.sha256);});
test('prepared/completion schema validation and independent read binding',()=>{const {receipt}=applied();validatePrepared(receipt.prepared);validateCompletion(receipt);assert.equal(receipt.prepared.final_recorded_at,'UNBOUND');assert.equal(receipt.prepared.after_fingerprint,'UNBOUND');assert.throws(()=>validatePrepared({...receipt.prepared,after_fingerprint:'fake'}));assert.throws(()=>prepared('bad',verifyFreeze()));});
test('prior LIVE-004 frozen package fingerprint and composition unchanged',async()=>{const {verifyFreeze:oldVerify}=await import('../injections/historical-batch-v1/freeze.js');assert.equal(oldVerify(),'1dbeec4e4719970d7254c4a7b5ba614651a9b13d4bd4fc88308c2b1368a94f69');const oldReview=JSON.parse(readFileSync(new URL('../injections/historical-batch-v1/dry-review.json',import.meta.url),'utf8'));const s=createEmptyProject({title:'old'});s.project.id=TARGET_PROJECT;s.current_state.project_id=TARGET_PROJECT;assert.deepEqual(previous.dry(s).review.records,oldReview.records);});
test('new package file-map fingerprint reproduces',()=>{assert.equal(verifyFreeze(),verifyFreeze());assert.match(verifyFreeze(),/^[0-9a-f]{64}$/);});
