import {it}from'node:test';import assert from'node:assert/strict';import {decomposeReality}from'../reality/canonical-translation.js';
import {createEmptyProject,applyPatch}from'../state-engine.js';import {proposeFromReality}from'../reality/propose.js';
import {ownershipRoles,quantityRole}from'../reality/semantic-roles.js';
for(const target of ['展示品','測器','輸送機材'])it('grammatical owner and physical custodian: '+target,()=>{const u=decomposeReality(`${target}の所有権は管理者Aにある。${target}を保管しているのは保管者Bであり、使用の許可は不明。`);assert.ok(u.some(x=>x.properties.owner_name==='管理者A'));assert.ok(u.some(x=>x.properties.custodian_name==='保管者B'));});
it('numeral suffix can identify a record count without becoming real people',()=>{assert.equal(quantityRole('','の入場記録に対して','人'),'record_count');assert.equal(quantityRole('名簿431人と実人数','の差','人'),'observed_count');});
it('nested report chain retains outer reporter, intermediary and reported observer',()=>{const u=decomposeReality('連絡員Cが「案内人Bが『観測員Aが破損を直接見た』と聞いた」と報告した。')[0];assert.equal(u.reporter,'連絡員C');assert.equal(u.properties.reported_observer_name,'観測員A');assert.deepEqual(u.properties.intermediary_names,['案内人B']);assert.deepEqual(u.eventKinds,[]);});
it('organization statement remains attributed instead of observed truth',()=>{const u=decomposeReality('運営組織の発表では「作業が完了した」。')[0];assert.equal(u.properties.source_organization_name,'運営組織');assert.equal(u.qualification,'reported');assert.deepEqual(u.eventKinds,[]);});
it('unverified social claim does not fabricate an observer identity',()=>{const u=decomposeReality('SNS投稿に「作業が完了した」とある。')[0];assert.equal(u.qualification,'reported');assert.equal(u.observer,undefined);assert.equal(u.properties.source_identity_verified,false);assert.deepEqual(u.eventKinds,[]);});
it('identifying containers does not invent an origin verification result',()=>{const u=decomposeReality('容器R1、ラベルL1、内容物C1、参加者P1、電子台帳E1を別対象として識別する。')[0];assert.equal(u.properties.contents_origin_verified,undefined);});
it('named object survives case particles instead of becoming a composite clause entity',()=>{const s=createEmptyProject({title:'Named anchor'});const p=proposeFromReality(s,{project_id:s.project.id,input_text:'試料Kを検査したところ成分Xは検出されなかった。'},'canonical');assert.ok('proposed_patch'in p.result);if('proposed_patch'in p.result){const n=applyPatch(s,p.result.proposed_patch);const sample=n.reality_entities.find(x=>x.label==='試料K');assert.ok(sample);assert.ok(n.reality_states.some(x=>x.kind==='target_entity'&&x.value===sample!.id));}});

it('coded nominal anchors end before particles or a following coded participant',()=>{for(const input of ['分析試料K21は参加者P21に由来すると鑑定で確認済み。','通信N4センサーの出力は73だった。']){const state=createEmptyProject({title:'nominal boundary'});const p=proposeFromReality(state,{project_id:state.project.id,input_text:input},'canonical');assert.ok('proposed_patch' in p.result);const next=applyPatch(state,p.result.proposed_patch);const label=input.startsWith('分析')?'分析試料K21':'通信N4センサー';assert.ok(next.reality_states.some(x=>x.kind==='target_entity'&&next.reality_entities.find(e=>e.id===x.value)?.label===label));}});
