/** Competing reported propositions. No historical Event/State or knowledge promotion. */
import {createHash} from 'node:crypto';
import {validateDataset,type HistoricalDataset} from '../substrate.js';
import {materializeRound3,validateDocumentary,traceDocumentary,type Round3} from '../round3/lineage.js';
export type Kind='observation'|'event_candidate'|'episode_alignment'|'temporal_evidence'|'spatial_evidence'|'quantity'|'contrast'|'independence'|'state_description'|'knowledge_stage'|'silence'|'modality_boundary'|'reconstruction';
export interface Record4 {id:string;kind:Kind;claim_ids:string[];record_ids:string[];limit:string;description:string;details:Record<string,unknown>}
export interface Round4 {schema_version:'historical-reality-experimental/round4';parents:Round3['parents'] & {round3_sha256:string};delta:Round3['delta'];documentary:Round3['documentary'];assets:Round3['assets'];records:Record4[];reconstruction_versions:{id:string;version:number;previous_version_id:string|null;proposition_ids:string[];change_reason:string}[]}
const keys=['actors','sources','claims','evidence_relations','actor_epistemic_records','reconstructions','interpretations','narratives'] as const;
const hash=(b:string)=>createHash('sha256').update(b).digest('hex');
export const documentaryAdapter=(r:Round4):Round3=>({schema_version:'historical-reality-experimental/round3',parents:r.parents,delta:r.delta,documentary:r.documentary,assets:r.assets});
export function materializeRound4(p1:string,p2:string,p3:string,r:Round4):HistoricalDataset {
 if(r.schema_version!=='historical-reality-experimental/round4'||hash(p3)!==r.parents.round3_sha256||hash(p1)!==r.parents.round1_sha256||hash(p2)!==r.parents.round2_sha256)throw new Error('Round4 parent/version integrity mismatch');
 const data=structuredClone(materializeRound3(p1,p2,JSON.parse(p3) as Round3));for(const k of keys)(data[k] as {id:string}[]).push(...structuredClone(r.delta[k]));validateDataset(data);validateRound4(data,r);return data;
}
export function validateRound4(data:HistoricalDataset,r:Round4):void {
 validateDocumentary(data,documentaryAdapter(r));const claims=new Map(data.claims.map(c=>[c.id,c]));const actors=new Set(data.actors.map(a=>a.id));
 const documentary=[...r.documentary.artifacts,...r.documentary.references,...r.documentary.lineage,...r.documentary.messages,...r.documentary.stages,...r.documentary.assessments,...r.documentary.gaps,...r.documentary.translation_checks,...r.documentary.reconstructions];
 const records=new Map(r.records.map(x=>[x.id,x]));const all=new Set([...documentary.map(x=>x.id),...records.keys()]);if(records.size!==r.records.length||all.size!==documentary.length+r.records.length)throw new Error('Duplicate Round4 record');
 const requireRecord=(id:string)=>{if(!all.has(id))throw new Error('Dangling Round4 record: '+id)};
 for(const c of r.delta.claims)if(!c.locator||!c.extraction.context||!c.assertion_layer)throw new Error('Atomic claim needs locator/context/attribution layer');
 for(const x of r.records){if(!x.id||!x.description||!x.limit||!x.claim_ids.length||!x.details||!['observation','event_candidate','episode_alignment','temporal_evidence','spatial_evidence','quantity','contrast','independence','state_description','knowledge_stage','silence','modality_boundary','reconstruction'].includes(x.kind))throw new Error('Scoped derived record required');x.claim_ids.forEach(c=>{if(!claims.has(c))throw new Error('Dangling claim')});x.record_ids.forEach(requireRecord);const d=x.details;
  if(d.actor_id!==undefined&&!actors.has(String(d.actor_id)))throw new Error('Unknown scoped actor');
  if(x.kind==='event_candidate'&&(d.canonical_event!==false||!d.source_description))throw new Error('Candidate cannot be canonical event');
  if(x.kind==='episode_alignment'){if(!['probably_same_episode_as','distinct_episode_from'].includes(String(d.relation))||!d.manual_basis||!Array.isArray(d.candidate_ids)||d.candidate_ids.length!==2||d.candidate_ids.some(id=>records.get(String(id))?.kind!=='event_candidate'))throw new Error('Manual episode alignment required');}
  if(x.kind==='temporal_evidence'){if(!d.raw||!d.time_role||!d.clock_standard||d.canonical_instant!==null||!d.conversion_method||!d.uncertainty)throw new Error('Raw temporal role/unknown clock boundary required');}
  if(x.kind==='spatial_evidence'){if(!d.raw||!['named_area','relative','diagram_relative','approximate_range'].includes(String(d.precision))||d.coordinates!==null)throw new Error('Source spatial precision cannot be synthesized');}
  if(x.kind==='quantity'){if(!d.unit||!d.scope||!['exact_reported','at_least_reported','approximate_reported','range_reported'].includes(String(d.operator))||!Array.isArray(d.values)||!d.values.length||d.values.some(v=>typeof v!=='number'||!Number.isFinite(v)||v<0)||d.reality_value!==null)throw new Error('Quantity requires unit/scope and no world value');}
  if(x.kind==='contrast'){if(!d.category||!d.alignment_limit||!Array.isArray(d.claim_pair)||d.claim_pair.length!==2||d.claim_pair.some(id=>!x.claim_ids.includes(String(id))))throw new Error('Contrast needs two rooted assertions/alignment');if(d.category==='direct_negation'){const [a,b]=d.claim_pair.map(id=>claims.get(String(id))!.reported_proposition as {topic:string;polarity:string});if(!a||!b||a.topic!==b.topic||new Set([a.polarity,b.polarity]).size!==2||![a.polarity,b.polarity].every(v=>['positive','negative'].includes(v))||!d.identity_alignment_id||records.get(String(d.identity_alignment_id))?.kind!=='episode_alignment'||!x.record_ids.includes(String(d.identity_alignment_id)))throw new Error('Direct negation requires opposite propositions and explicit identity alignment');}}
  if(x.kind==='independence'&&(!d.proposition_scope||!d.assessment||d.independent_source_count!==null))throw new Error('Independence is proposition-scoped, not source counting');
  if(x.kind==='state_description'&&(!d.state_role||!d.target||d.canonical_state!==false))throw new Error('Attributed state only');
  if(x.kind==='knowledge_stage'&&(!d.actor_id||!d.stage||!d.payload||d.knowledge_inferred!==false||!d.time_placement))throw new Error('Actor/payload-scoped stage boundary required');
  if(x.kind==='silence'&&(!d.source_purpose||!d.completeness||d.absence_inferred!==false))throw new Error('Silence cannot infer absence');
  if(x.kind==='modality_boundary'&&(d.image_inspected!==false||d.event_identity_confirmed!==false))throw new Error('Catalogue cannot become image/event evidence');
  if(x.kind==='reconstruction'){if(!['probable','contested','possible','unresolved'].includes(String(d.status))||!Array.isArray(d.supporting_claim_ids)||!d.supporting_claim_ids.length||!Array.isArray(d.contradicting_claim_ids)||[...d.supporting_claim_ids,...d.contradicting_claim_ids].some(id=>!x.claim_ids.includes(String(id)))||!Array.isArray(d.alternatives)||!d.alternatives.length||!d.rationale||!d.temporal_uncertainty||!d.spatial_uncertainty||!d.source_identity_certainty||!d.source_content_certainty||!d.reality_certainty)throw new Error('Reconstruction needs retained support/opposition/uncertainties/alternatives');}
 }
 const active=new Set<string>(),seen=new Set<string>();const walk=(id:string)=>{if(active.has(id))throw new Error('Round4 provenance cycle');if(seen.has(id))return;active.add(id);records.get(id)?.record_ids.forEach(walk);active.delete(id);seen.add(id)};records.forEach((_,id)=>walk(id));
 const versions=new Map<string,Round4['reconstruction_versions'][number]>();for(const v of r.reconstruction_versions){if(!v.id||versions.has(v.id)||v.version<1||!Number.isInteger(v.version)||!v.proposition_ids.length||!v.change_reason||v.proposition_ids.some(id=>records.get(id)?.kind!=='reconstruction'))throw new Error('Versioned reconstruction required');if(v.previous_version_id===null){if(v.version!==1)throw new Error('Initial version must be 1');}else {const p=versions.get(v.previous_version_id);if(!p||v.version!==p.version+1)throw new Error('Version ancestry required');}versions.set(v.id,v);}
}
export function traceRound4(data:HistoricalDataset,r:Round4,id:string){validateRound4(data,r);const map=new Map(r.records.map(x=>[x.id,x]));const roots=new Set<string>(),seen=new Set<string>(),documentary:any[]=[];const walk=(key:string)=>{if(seen.has(key))return;seen.add(key);const x=map.get(key);if(x){x.claim_ids.forEach(c=>roots.add(c));x.record_ids.forEach(walk)}else{const t=traceDocumentary(data,documentaryAdapter(r),key);t.claims.forEach(c=>roots.add(c.id));documentary.push(t)}};if(!map.has(id))return traceDocumentary(data,documentaryAdapter(r),id);walk(id);const cs=data.claims.filter(c=>roots.has(c.id));return {id,records:[...seen].filter(k=>map.has(k)).map(k=>map.get(k)!),documentary,claims:cs,relations:data.evidence_relations.filter(e=>roots.has(e.claim_id)),sources:data.sources.filter(s=>cs.some(c=>c.source_id===s.id)),boundary:'Attributed evidence and versioned reconstruction; no canonical event identity, world quantities, historical knowledge or original authentication inferred.'};}
/** Reject retroactive edits; new evidence must append a version and new proposition IDs. */
export function validateVersionAppend(previous:Round4,next:Round4){for(const v of previous.reconstruction_versions){const n=next.reconstruction_versions.find(x=>x.id===v.id);if(JSON.stringify(n)!==JSON.stringify(v))throw new Error('Prior reconstruction version changed');for(const id of v.proposition_ids)if(JSON.stringify(next.records.find(x=>x.id===id))!==JSON.stringify(previous.records.find(x=>x.id===id)))throw new Error('Prior proposition changed');}}
export function actorMilitaryAt(data:HistoricalDataset,r:Round4,actor:string,day:string){validateRound4(data,r);if(!data.actors.some(a=>a.id===actor)||!/^\d{4}-\d{2}-\d{2}$/.test(day)||Number.isNaN(Date.parse(day+'T00:00:00Z'))||new Date(day+'T00:00:00Z').toISOString().slice(0,10)!==day)throw new Error('Known actor and valid Gregorian day required');const rows=r.records.filter(x=>x.kind==='knowledge_stage'&&x.details.actor_id===actor);return {actor,day,before:rows.filter(x=>typeof x.details.normalized_day==='string'&&x.details.normalized_day<day),same_day_order_unknown:rows.filter(x=>x.details.normalized_day===day),unplaced:rows.filter(x=>typeof x.details.normalized_day!=='string'),knowledge:'not_inferred',absence:'not_inferred'};}
