import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createEmptyProject,applyPatch} from '../../../state-engine.js';
import {saveProject,loadProject} from '../../../file-store.js';
import {getEvidenceForClaim} from '../../../reality/epistemic.js';
import {projectSourceAssertions} from '../substrate.js';
import {materializeRound4,traceRound4,actorMilitaryAt,type Round4} from './reconstruction.js';
const here=dirname(fileURLToPath(import.meta.url)),read=(p:string)=>readFileSync(resolve(here,p),'utf8'),hash=(b:Buffer|string)=>createHash('sha256').update(b).digest('hex');
const bytes=read('round4.dataset.json'),round=JSON.parse(bytes) as Round4,p1=read('../round1.dataset.json'),p2=read('../round2/round2.dataset.json'),p3=read('../round3/round3.dataset.json');const data=materializeRound4(p1,p2,p3,round);
if(hash(read('../round1.landscape.json'))!==round.parents.landscape_sha256)throw new Error('Landscape changed');
let assetCount=0;for(const [base,assets] of [[here,round.assets],[resolve(here,'../round3'),JSON.parse(p3).assets],[resolve(here,'../round2'),JSON.parse(p2).assets]] as [string,Round4['assets']][]){for(const a of assets){const b=readFileSync(resolve(base,a.path));if(hash(b)!==a.sha256||b.length!==a.bytes)throw new Error('Asset changed: '+a.path);if(a.format==='pdf'&&b.subarray(0,5).toString()!=='%PDF-')throw new Error('Not PDF');if(a.format==='png'&&b.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw new Error('Not PNG');if(a.format==='json')JSON.parse(b.toString());if(a.format==='html'&&!/<(?:!doctype\s+html|html|head|body)/i.test(b.toString('latin1')))throw new Error('Not HTML');assetCount++;}}
const output=resolve(process.argv[2]??resolve(here,'replay'));mkdirSync(output,{recursive:true});const write=(name:string,v:unknown)=>writeFileSync(resolve(output,name),JSON.stringify(v,null,2)+'\n');write('sidecar.reload.json',round);const loadedRound=JSON.parse(readFileSync(resolve(output,'sidecar.reload.json'),'utf8')) as Round4;if(JSON.stringify(materializeRound4(p1,p2,p3,loadedRound))!==JSON.stringify(data))throw new Error('Reload changed meaning');
const d=round.documentary,doc=[...d.artifacts,...d.references,...d.lineage,...d.messages,...d.stages,...d.assessments,...d.gaps,...d.translation_checks,...d.reconstructions];const traces=[...round.records,...doc].map(x=>traceRound4(data,loadedRound,x.id));if(traces.some(t=>!t.claims.length||!t.sources.length))throw new Error('Derived root missing');
const p=createEmptyProject({title:'Historical Reality — Round4',summary:'Parallel military reports and versioned reconstruction'});p.project.id='19041904-1904-4904-8904-190419044004';p.current_state.project_id=p.project.id;const patch=projectSourceAssertions(data,p,'2026-09-14T00:00:00.000Z');const state=applyPatch(p,patch);saveProject(state,{storageDir:output});const loaded=loadProject(state.project.id,{storageDir:output});if(loaded.reality_events.length||loaded.reality_states.length||loaded.claims.some(c=>getEvidenceForClaim(loaded,c.id).supports.length!==1))throw new Error('Unsafe/lossy core projection trace');
write('materialized.dataset.json',data);write('evidence-traces.json',traces);write('source-assertions.patch.json',patch);write('contrasts.json',round.records.filter(x=>x.kind==='contrast'));write('reconstruction-v1.json',{versions:round.reconstruction_versions,propositions:round.records.filter(x=>x.kind==='reconstruction')});write('actor-queries.json',['r4:flagship-watch','r4:novik','r4:cherkasov','togo','navy-minister','jp-cabinet','r4:kamimura'].map(a=>actorMilitaryAt(data,round,a,'1904-02-09')));write('negative-search-records.json',d.searches.map(s=>traceRound4(data,round,s.id)));
const result={dataset_sha256:hash(bytes),counts:{actors:data.actors.length,sources:data.sources.length,claims:data.claims.length,relations:data.evidence_relations.length,new_actors:round.delta.actors.length,new_sources:round.delta.sources.length,new_claims:round.delta.claims.length,records:round.records.length,record_kinds:Object.fromEntries([...new Set(round.records.map(x=>x.kind))].map(k=>[k,round.records.filter(x=>x.kind===k).length])),documentary_records:doc.length,searches:d.searches.length,assets:round.assets.length,reconstruction_versions:round.reconstruction_versions.length},derived_traces:traces.length,assets_validated_including_parents:assetCount,parent_integrity:'Round1–3 datasets and Round1 landscape SHA256 matched; inherited assets matched',canonical_projection:{claims:loaded.claims.length,historical_events:0,historical_states:0,scope:'Source content only; inherited0.95isuncalibratedtext-attributionestimate'},validation:'serialize/reload/materialize equality; every derived record traces to source; asset hash/size/magic; file-store reload; core support routes retained',limits:['Novik representation partial','Russian local clock and calendar not independently calibrated','Original logs/messages/repair records not inspected','Pallada/Pallida alignment probable only','Photograph uninspected; catalogue only','No government reading/knowledge inferred']};write('validation.json',result);console.log(JSON.stringify(result,null,2));
