/** Documentary sidecar: attributed evidence, never inferred historical custody or knowledge. */
import {createHash} from 'node:crypto';
import {validateDataset,type HistoricalDataset,type HistoricalTime} from '../substrate.js';
import {materializeRound2,type Round2} from '../round2/propagation.js';
type Basis={claim_ids:string[];limit:string};
type TimeRole={role:string;time:HistoricalTime;claim_ids:string[]};
export type Artifact=Basis & {id:string;kind:string;source_ids:string[];inspection:string;language:{value:string;basis:string};original_status:'not_a_historical_original'|'unverified_archival_document'|'catalogued_not_inspected';identity:{namespace:string;value:string;assigned_context:string}[];provenance_status:string;authenticity:'unresolved';temporal_roles:TimeRole[]};
export type Reference=Basis & {id:string;label:string;locator:string;existence:'referenced_not_verified';unknown_reason:string};
export type Lineage=Basis & {id:string;from_id:string;to:{kind:'artifact'|'reference';id:string};relation:'digitized_from'|'transcribed_from'|'translated_from'|'quoted_from'|'cites_for'|'claims_to_reproduce';attestation:'observed_comparison'|'publisher_assertion'|'citation_only';status:'partial_correspondence'|'asserted_not_verified';scope:string};
type ActorRef=string|{status:'unknown';reason:string};
export type Stage=Basis & {id:string;message_id:string;stage:'addressed_to'|'dispatched'|'held_at_location'|'delivered_to'|'possessed_by'|'receipt_acknowledged'|'receipt_annotated'|'reported_to'|'read_by';actor_id:ActorRef;actor_role:string;additional_actor_scopes?:Record<string,ActorRef>;attestation_form:'source_asserts'|'source_reports_actor_assertion'|'later_reconstruction'|'retrospective_actor_assertion';time:HistoricalTime;time_role:string};
export interface Round3 {
 schema_version:'historical-reality-experimental/round3';parents:{round1_sha256:string;round2_sha256:string;landscape_sha256:string};delta:Round2['delta'];
 documentary:{artifacts:Artifact[];references:Reference[];lineage:Lineage[];messages:(Basis & {id:string;label:string;identity_status:string})[];stages:Stage[];assessments:(Basis & {id:string;target:{kind:'source_content'|'documentary_identity'|'external_reality';id:string};status:'strongly_established'|'possible'|'unresolved';proposition:string})[];gaps:(Basis & {id:string;target_id:string;role:string;unknown_reason:string;reason:string})[];searches:{id:string;what:string;where:string;query_or_locator:string;searched_on:string;result:string;classification:string;limitation:string;source_ids:string[];absence_inference:false}[];reconstructions:(Basis & {id:string;domain:'documentary'|'historical_reality'|'knowledge';proposition:string;status:'strongly_established'|'possible'|'unresolved';record_ids:string[]})[];translation_checks:(Basis & {id:string;from_id:string;to_id:string;operations:{dimension:string;observation:string}[];status:string})[]};
 assets:{id:string;source_id:string;path:string;sha256:string;bytes:number;format:'pdf'|'png'|'html'|'json';origin_url:string;inspection:string}[];
}
const hash=(bytes:string)=>createHash('sha256').update(bytes).digest('hex');
const keys=['actors','sources','claims','evidence_relations','actor_epistemic_records','reconstructions','interpretations','narratives'] as const;
export function materializeRound3(parent1:string,parent2:string,round:Round3):HistoricalDataset {
 if(round.schema_version!=='historical-reality-experimental/round3')throw new Error('Unsupported Round3 version');
 if(hash(parent1)!==round.parents.round1_sha256||hash(parent2)!==round.parents.round2_sha256)throw new Error('Parent integrity mismatch');
 const data=structuredClone(materializeRound2(parent1,JSON.parse(parent2) as Round2));
 for(const key of keys)(data[key] as {id:string}[]).push(...structuredClone(round.delta[key]));
 validateDataset(data);validateDocumentary(data,round);return data;
}
const day=(value:string)=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(value+'T00:00:00Z'))&&new Date(value+'T00:00:00Z').toISOString().slice(0,10)===value;
export function validateDocumentary(data:HistoricalDataset,round:Round3):void {
 const d=round.documentary;const claims=new Set(data.claims.map(x=>x.id)),sources=new Set(data.sources.map(x=>x.id)),actors=new Set(data.actors.map(x=>x.id));
 const artifacts=new Map(d.artifacts.map(x=>[x.id,x])),refs=new Map(d.references.map(x=>[x.id,x])),messages=new Map(d.messages.map(x=>[x.id,x]));
 const records=new Map<string,Basis>();
 const requireRef=(set:Set<string>,id:string)=>{if(!set.has(id))throw new Error(`Dangling documentary reference: ${id}`)};
 const basis=(r:Basis & {id:string})=>{if(!r.id||records.has(r.id))throw new Error('Duplicate documentary ID');records.set(r.id,r);if(!r.limit||!r.claim_ids.length)throw new Error('Derived record requires basis and limit');r.claim_ids.forEach(x=>requireRef(claims,x));};
 const time=(t:HistoricalTime)=>{if(!t.raw||!['day','year','unknown'].includes(t.precision))throw new Error('Raw temporal representation required');if(typeof t.normalized_day==='string'){if(!day(t.normalized_day)||t.precision!=='day')throw new Error('Temporal precision synthesis');}else if(t.normalized_day?.status!=='unknown'||!t.normalized_day.reason)throw new Error('Unknown time requires reason');};
 for(const a of d.artifacts){basis(a);if(!a.source_ids.length)throw new Error('Artifact requires located source');a.source_ids.forEach(x=>requireRef(sources,x));if(!a.claim_ids.some(id=>a.source_ids.includes(data.claims.find(c=>c.id===id)!.source_id)))throw new Error('Artifact has no source-local basis');if(!a.inspection||!a.identity.length||a.identity.some(x=>!x.namespace||!x.value||!x.assigned_context)||!a.language.value||!a.language.basis||!a.provenance_status||a.authenticity!=='unresolved'||!['not_a_historical_original','unverified_archival_document','catalogued_not_inspected'].includes(a.original_status))throw new Error('Artifact identity/inspection boundary required');a.temporal_roles.forEach(t=>{if(!t.role||!t.claim_ids.length)throw new Error('Temporal role requires evidence');time(t.time);t.claim_ids.forEach(id=>requireRef(claims,id));});}
 for(const r of d.references){basis(r);if(r.existence!=='referenced_not_verified'||!r.unknown_reason||!r.locator||!r.label)throw new Error('Unverified reference cannot become an original artifact');}
 for(const m of d.messages){basis(m);if(!m.label||!m.identity_status)throw new Error('Message identity boundary required');}
 for(const e of d.lineage){basis(e);if(!artifacts.has(e.from_id)||e.from_id===e.to.id||(e.to.kind==='artifact'?!artifacts.has(e.to.id):e.to.kind!=='reference'||!refs.has(e.to.id)))throw new Error('Invalid upstream endpoint');if(!['digitized_from','transcribed_from','translated_from','quoted_from','cites_for','claims_to_reproduce'].includes(e.relation)||!['observed_comparison','publisher_assertion','citation_only'].includes(e.attestation)||!['partial_correspondence','asserted_not_verified'].includes(e.status)||!e.scope)throw new Error('Scoped transformation required');if(e.to.kind==='reference'&&(e.status!=='asserted_not_verified'||e.attestation==='observed_comparison'))throw new Error('Reference endpoint is unverified');if(e.relation==='translated_from'&&e.to.kind==='artifact'&&artifacts.get(e.from_id)!.language.value===artifacts.get(e.to.id)!.language.value)throw new Error('Translation requires evidenced language transformation');}
 const actorRef=(actor:ActorRef)=>{if(typeof actor==='string')requireRef(actors,actor);else if(actor?.status!=='unknown'||!actor.reason)throw new Error('Unspecified actor requires reason');};
 for(const s of d.stages){basis(s);actorRef(s.actor_id);if(!s.actor_role)throw new Error('Actor role required');for(const [role,actor] of Object.entries(s.additional_actor_scopes??{})){if(!role)throw new Error('Additional actor role required');actorRef(actor);}if(!messages.has(s.message_id)||!['addressed_to','dispatched','held_at_location','delivered_to','possessed_by','receipt_acknowledged','receipt_annotated','reported_to','read_by'].includes(s.stage)||!['source_asserts','source_reports_actor_assertion','later_reconstruction','retrospective_actor_assertion'].includes(s.attestation_form)||!s.time_role)throw new Error('Attested payload-specific stage required');time(s.time);if(s.stage==='read_by'&&!s.claim_ids.some(id=>data.claims.find(c=>c.id===id)!.predicate==='explicit_reading_assertion'))throw new Error('Reading cannot be synthesized from receipt or address');}
 const targetIds=new Set([...artifacts.keys(),...refs.keys(),...messages.keys(),...claims,...d.stages.map(x=>x.id),...d.lineage.map(x=>x.id)]);
 for(const a of d.assessments){basis(a);requireRef(targetIds,a.target.id);if(!['source_content','documentary_identity','external_reality'].includes(a.target.kind)||!['strongly_established','possible','unresolved'].includes(a.status)||!a.proposition)throw new Error('Independent certainty target required');if(a.target.kind==='source_content'){requireRef(claims,a.target.id);if(!a.claim_ids.includes(a.target.id))throw new Error('Content assessment must include target claim');}}
 for(const g of d.gaps){basis(g);requireRef(targetIds,g.target_id);if(!g.role||!g.unknown_reason||!g.reason)throw new Error('Gap reason required');}
 for(const c of d.translation_checks){basis(c);if(!artifacts.has(c.from_id)||!artifacts.has(c.to_id)||!c.operations.length||c.operations.some(o=>!o.dimension||!o.observation)||!c.status)throw new Error('Translation comparison scope required');}
 for(const s of d.searches){if(!s.id||records.has(s.id)||!s.what||!s.where||!s.query_or_locator||!day(s.searched_on)||!s.result||!s.classification||!s.limitation||s.absence_inference!==false)throw new Error('Search failure cannot establish historical absence');s.source_ids.forEach(x=>requireRef(sources,x));records.set(s.id,{claim_ids:[],limit:s.limitation});}
 for(const r of d.reconstructions){basis(r);if(!['documentary','historical_reality','knowledge'].includes(r.domain)||!['strongly_established','possible','unresolved'].includes(r.status)||!r.proposition||!r.record_ids.length)throw new Error('Reconstruction domain required');}
 for(const r of d.reconstructions)r.record_ids.forEach(id=>{if(!records.has(id)||id===r.id)throw new Error('Dangling reconstruction basis');if(d.reconstructions.some(x=>x.id===id))throw new Error('No automatic cross-domain reconstruction inheritance');});
 const visited=new Set<string>(),active=new Set<string>();const visit=(id:string)=>{if(active.has(id))throw new Error('Documentary lineage cycle');if(visited.has(id))return;active.add(id);for(const e of d.lineage.filter(x=>x.from_id===id&&x.to.kind==='artifact'))visit(e.to.id);active.delete(id);visited.add(id);};artifacts.forEach((_,id)=>visit(id));
 for(const a of round.assets){requireRef(sources,a.source_id);if(!a.id||!a.path||a.path.startsWith('/')||a.path.split('/').includes('..')||!/^https:\/\//.test(a.origin_url)||!/^[a-f0-9]{64}$/.test(a.sha256)||a.bytes<1||!['pdf','png','html','json'].includes(a.format)||!a.inspection)throw new Error('Asset provenance required');}
}
/** Complete derived-basis closure, including upstream endpoints and explicit terminal gaps. */
export function traceDocumentary(data:HistoricalDataset,round:Round3,id:string){
 validateDocumentary(data,round);const d=round.documentary;
 const search=d.searches.find(x=>x.id===id);
 if(search)return {id,records:[search],claims:[],relations:[],sources:data.sources.filter(s=>search.source_ids.includes(s.id)),terminal_references:[],boundary:'Search diagnostic with declared scope and limitations, not evidence of historical absence or actor ignorance.'};
 const all=new Map<string,Basis & {id:string}>([...d.artifacts,...d.references,...d.messages,...d.lineage,...d.stages,...d.assessments,...d.gaps,...d.translation_checks,...d.reconstructions].map(x=>[x.id,x]));
 const roots=new Set<string>(),seen=new Set<string>();const walk=(key:string)=>{if(seen.has(key))return;const r=all.get(key);if(!r)throw new Error(`Unknown derived record: ${key}`);seen.add(key);r.claim_ids.forEach(c=>roots.add(c));
  const a=d.artifacts.find(x=>x.id===key);if(a){a.temporal_roles.forEach(t=>t.claim_ids.forEach(c=>roots.add(c)));for(const e of d.lineage.filter(x=>x.from_id===key))walk(e.id);for(const g of d.gaps.filter(x=>x.target_id===key))walk(g.id);}
  const e=d.lineage.find(x=>x.id===key);if(e){walk(e.from_id);walk(e.to.id);}
  const s=d.stages.find(x=>x.id===key);if(s)walk(s.message_id);
  const assessment=d.assessments.find(x=>x.id===key);if(assessment){if(all.has(assessment.target.id))walk(assessment.target.id);else roots.add(assessment.target.id);}
  const g=d.gaps.find(x=>x.id===key);if(g&&all.has(g.target_id))walk(g.target_id);
  const t=d.translation_checks.find(x=>x.id===key);if(t){walk(t.from_id);walk(t.to_id);}
  d.reconstructions.find(x=>x.id===key)?.record_ids.forEach(walk);
 };walk(id);const claims=data.claims.filter(c=>roots.has(c.id));const sourceIds=new Set(claims.map(c=>c.source_id));
 return {id,records:[...seen].map(x=>all.get(x)!),claims,relations:data.evidence_relations.filter(x=>roots.has(x.claim_id)),sources:data.sources.filter(x=>sourceIds.has(x.id)),terminal_references:d.references.filter(x=>seen.has(x.id)),boundary:'Source content and reference attribution only; no original authentication, historical truth or actor reading inferred.'};
}
export function actorStagesAt(data:HistoricalDataset,round:Round3,actor:string,message:string,queryDay:string){
 validateDocumentary(data,round);if(!data.actors.some(x=>x.id===actor)||!round.documentary.messages.some(x=>x.id===message)||!day(queryDay))throw new Error('Known actor/message and Gregorian day required');
 const rows=round.documentary.stages.filter(x=>(x.actor_id===actor||Object.values(x.additional_actor_scopes??{}).includes(actor))&&x.message_id===message);
 return {actor_id:actor,message_id:message,day:queryDay,documented_before_day:rows.filter(x=>typeof x.time.normalized_day==='string'&&x.time.normalized_day<queryDay),same_day_order_unknown:rows.filter(x=>x.time.normalized_day===queryDay),unplaced:rows.filter(x=>typeof x.time.normalized_day!=='string'),reading:'not_inferred',knowledge:'not_inferred',limit:'Attributed records, including later recollections. Empty results do not prove ignorance; delivery does not entail reading.'};
}
